/**
 * Human Atlas 3D - Anatomical Telemetry & Knowledgebase Data
 * 2,234 Modeled Pieces | DBCLS BodyParts3D 4.0 Reference Taxonomy
 */

export const ANATOMICAL_SYSTEMS = [
  {
    id: 'skeletal',
    name: 'Skeleton',
    latin: 'Systema skeletale',
    count: 296,
    color: '#e2d9ba',
    category: 'skeleton',
    description: 'Bones form the supporting framework of the body, protect organs, and provide attachment points for muscles. Their internal tissue also stores minerals and produces blood cells.'
  },
  {
    id: 'muscular',
    name: 'Muscles',
    latin: 'Systema musculare',
    count: 402,
    color: '#a85b50',
    category: 'all',
    description: 'Skeletal muscles generate movement by pulling on their attachments. Together with tendons, they move joints, stabilize posture, and produce heat.'
  },
  {
    id: 'cardiac',
    name: 'Heart',
    latin: 'Cor',
    count: 23,
    color: '#b96760',
    category: 'organs',
    description: 'The heart is a muscular pump with four chambers. Its valves direct blood forward through the pulmonary and systemic circuits.'
  },
  {
    id: 'sensory',
    name: 'Sensory organs',
    latin: 'Organa sensuum',
    count: 45,
    color: '#b0c8ce',
    category: 'organs',
    description: 'These structures contribute to special senses, including sight, hearing, and balance. Specialized tissues detect stimuli and convey signals through the cranial nerves.'
  },
  {
    id: 'arterial',
    name: 'Arteries',
    latin: 'Arteriae systemicae',
    count: 639,
    color: '#c05245',
    category: 'all',
    description: 'High-pressure systemic arterial tree conveying oxygenated blood from the ascending aorta to peripheral micro-arterioles.'
  },
  {
    id: 'venous',
    name: 'Veins',
    latin: 'Venae systemicae',
    count: 404,
    color: '#527c9f',
    category: 'all',
    description: 'Venous return conduits collecting blood from peripheral tissues; superior and inferior venae cavae return deoxygenated blood to the right atrium.'
  },
  {
    id: 'nervous',
    name: 'Nervous system',
    latin: 'Systema nervosum',
    count: 139,
    color: '#d8b565',
    category: 'all',
    description: 'The brain, spinal cord, and peripheral nerves carry and process signals. They support sensation, movement, coordination, and visceral regulation.'
  },
  {
    id: 'respiratory',
    name: 'Respiratory',
    latin: 'Systema respiratorium',
    count: 119,
    color: '#b98991',
    category: 'organs',
    description: 'The airways conduct air to the lungs, where gas exchange occurs across alveolar membranes. Breathing relies on pressure changes generated by the diaphragm and intercostals.'
  },
  {
    id: 'digestive',
    name: 'Digestive',
    latin: 'Systema digestorium',
    count: 97,
    color: '#b8916b',
    category: 'organs',
    description: 'The alimentary canal breaks down nutrients, absorbs water and vital electrolytes, and moves waste onward. Accessory glands contribute bile and digestive enzymes.'
  },
  {
    id: 'urinary',
    name: 'Urinary',
    latin: 'Systema urinarium',
    count: 6,
    color: '#b47961',
    category: 'organs',
    description: 'The kidneys filter blood, regulate electrolyte balance, and produce urine. Fluid travels through the ureters into the bladder for storage.'
  },
  {
    id: 'lymphatic',
    name: 'Lymphatic',
    latin: 'Systema lymphoideum',
    count: 3,
    color: '#879f7c',
    category: 'all',
    description: 'Lymphatic vessels return excess interstitial fluid to the circulation and support systemic immune surveillance.'
  },
  {
    id: 'endocrine',
    name: 'Endocrine',
    latin: 'Systema endocrinum',
    count: 4,
    color: '#c5a09a',
    category: 'organs',
    description: 'Endocrine organs secrete regulatory hormones directly into the bloodstream to coordinate metabolism, growth, and physiological homeostasis.'
  },
  {
    id: 'reproductive',
    name: 'Reproductive',
    latin: 'Organa genitalia',
    count: 12,
    color: '#bda098',
    category: 'organs',
    description: 'Internal pelvic reproductive structures including prostate, deferent ducts, and seminal vesicles (external private parts omitted for modesty).'
  },
  {
    id: 'integumentary',
    name: 'Body surface (Skin)',
    latin: 'Integumentum commune',
    count: 5,
    color: '#ba9b7d',
    category: 'all',
    description: 'The external body surface provides protective barrier defense, thermoregulation, and defines the athletic human male silhouette.'
  },
  {
    id: 'connective',
    name: 'Connective tissue',
    latin: 'Textus connectivus',
    count: 40,
    color: '#aec3bb',
    category: 'skeleton',
    description: 'Cartilage, ligaments, and fibrous membranes providing structural reinforcement, joint articulation, and load distribution.'
  }
];

export const EXPLANATIONS = {
  'heart': 'A muscular pump in the chest. Its right side sends blood to the lungs; its left side sends blood through the systemic circulation.',
  'liver': 'A large organ beneath the right side of the diaphragm. It processes absorbed nutrients, produces bile, and synthesizes blood proteins.',
  'brain': 'The central organ of the nervous system. Its interconnected cerebral regions support cognition, movement, memory, and sensory processing.',
  'stomach': 'A muscular reservoir between the esophagus and small intestine that churns food with gastric acid and proteolytic enzymes.',
  'spleen': 'A lymphoid organ in the left hypochondrium that filters aged erythrocytes and mounts adaptive immune responses.',
  'pancreas': 'An exocrine and endocrine gland nestled in the C-loop of the duodenum, secreting digestive enzymes and insulin/glucagon.',
  'urinary bladder': 'A distensible muscular reservoir in the pelvis that stores urine arriving from the kidneys.',
  'trachea': 'The cartilaginous windpipe connecting the larynx to the principal bronchi.',
  'diaphragm': 'The primary musculotendinous dome separating the thoracic and abdominal cavities, crucial for negative-pressure breathing.',
  'skin': 'The protective outer envelope of the human body, exhibiting athletic superficial muscular contours.'
};

export function getSystemInfo(systemId) {
  return ANATOMICAL_SYSTEMS.find(s => s.id === systemId) || {
    id: systemId,
    name: systemId,
    latin: 'Anatomia',
    color: '#aebbb8',
    description: 'Anatomical structure belonging to the ' + systemId + ' system.'
  };
}

export function getPartDossier(part) {
  const sys = getSystemInfo(part.system);
  const expl = EXPLANATIONS[part.name.toLowerCase()] || sys.description;

  const minY = part.bounds[0][1];
  const maxY = part.bounds[1][1];
  const midY = (minY + maxY) / 2;

  let region = 'General Anatomy';
  if (midY > 1.50) region = 'Head & Craniofacial';
  else if (midY > 1.35) region = 'Neck & Cervical';
  else if (midY > 1.05) region = 'Thorax & Chest';
  else if (midY > 0.85) region = 'Abdomen & Pelvis';
  else if (midY > 0.45) region = 'Thigh & Knee';
  else region = 'Leg & Foot';

  return {
    id: part.id,
    conceptId: part.conceptId,
    name: part.name,
    systemId: part.system,
    systemName: sys.name,
    systemColor: sys.color,
    latin: part.conceptId ? (part.name + ' (' + part.conceptId + ')') : part.name,
    region: region,
    functionText: expl,
    clinicalText: 'FMA Concept: ' + (part.conceptId || 'Standard') + '. Segmented from DBCLS whole-body MRI/CT scan.',
    vesselsText: sys.name + ' · Segmented 3D Mesh (' + part.vertexCount.toLocaleString() + ' vertices, ' + Math.round(part.indexCount / 3).toLocaleString() + ' triangles)'
  };
}
