# Step 1: Skeleton (296) & Muscles (402)
lines = []
def a(s):
    lines.append(s)

a('  // 1. SKELETON (296)')
a('  const cranial = [')
a('    { name: \'Frontal Bone (L)\', latin: \'Os frontale sin.\', pos: [-0.035, 1.78, 0.05], scale: [0.042, 0.04, 0.04] },')
a('    { name: \'Frontal Bone (R)\', latin: \'Os frontale dex.\', pos: [0.035, 1.78, 0.05], scale: [0.042, 0.04, 0.04] },')
a('    { name: \'Parietal Bone (L)\', latin: \'Os parietale sin.\', pos: [-0.05, 1.81, -0.01], scale: [0.038, 0.045, 0.05] },')
a('    { name: \'Parietal Bone (R)\', latin: \'Os parietale dex.\', pos: [0.05, 1.81, -0.01], scale: [0.038, 0.045, 0.05] },')
a('    { name: \'Occipital Bone\', latin: \'Os occipitale\', pos: [0, 1.76, -0.06], scale: [0.058, 0.048, 0.035] },')
a('    { name: \'Temporal Bone (L)\', latin: \'Os temporale sin.\', pos: [-0.065, 1.73, -0.01], scale: [0.02, 0.035, 0.04] },')
a('    { name: \'Temporal Bone (R)\', latin: \'Os temporale dex.\', pos: [0.065, 1.73, -0.01], scale: [0.02, 0.035, 0.04] },')
a('    { name: \'Sphenoid Bone (L)\', latin: \'Os sphenoidale sin.\', pos: [-0.04, 1.74, 0.03], scale: [0.024, 0.02, 0.024] },')
a('    { name: \'Sphenoid Bone (R)\', latin: \'Os sphenoidale dex.\', pos: [0.04, 1.74, 0.03], scale: [0.024, 0.02, 0.024] },')
a('    { name: \'Ethmoid Bone\', latin: \'Os ethmoidale\', pos: [0, 1.74, 0.045], scale: [0.018, 0.02, 0.02] },')
a('    { name: \'Nasal Bone (L)\', latin: \'Os nasale sin.\', pos: [-0.01, 1.735, 0.075], scale: [0.008, 0.02, 0.01] },')
a('    { name: \'Nasal Bone (R)\', latin: \'Os nasale dex.\', pos: [0.01, 1.735, 0.075], scale: [0.008, 0.02, 0.01] },')
a('    { name: \'Zygomatic Bone (L)\', latin: \'Os zygomaticum sin.\', pos: [-0.05, 1.71, 0.05], scale: [0.02, 0.025, 0.02] },')
a('    { name: \'Zygomatic Bone (R)\', latin: \'Os zygomaticum dex.\', pos: [0.05, 1.71, 0.05], scale: [0.02, 0.025, 0.02] },')
a('    { name: \'Maxilla (L)\', latin: \'Maxilla sin.\', pos: [-0.025, 1.68, 0.055], scale: [0.024, 0.025, 0.03] },')
a('    { name: \'Maxilla (R)\', latin: \'Maxilla dex.\', pos: [0.025, 1.68, 0.055], scale: [0.024, 0.025, 0.03] },')
a('    { name: \'Palatine Bone (L)\', latin: \'Os palatinum sin.\', pos: [-0.015, 1.69, 0.03], scale: [0.014, 0.01, 0.02] },')
a('    { name: \'Palatine Bone (R)\', latin: \'Os palatinum dex.\', pos: [0.015, 1.69, 0.03], scale: [0.014, 0.01, 0.02] },')
a('    { name: \'Lacrimal Bone (L)\', latin: \'Os lacrimale sin.\', pos: [-0.02, 1.73, 0.06], scale: [0.008, 0.012, 0.008] },')
a('    { name: \'Lacrimal Bone (R)\', latin: \'Os lacrimale dex.\', pos: [0.02, 1.73, 0.06], scale: [0.008, 0.012, 0.008] },')
a('    { name: \'Mandible (L)\', latin: \'Mandibula sin.\', pos: [-0.035, 1.63, 0.035], scale: [0.028, 0.035, 0.042] },')
a('    { name: \'Mandible (R)\', latin: \'Mandibula dex.\', pos: [0.035, 1.63, 0.035], scale: [0.028, 0.035, 0.042] }')
a('  ];')
a('  cranial.forEach(b => addPiece({ name: b.name, latin: b.latin, systemKey: \'SKELETON\', subCategory: \'Cranium\', geo: geoBox, mat: materials.skeleton, pos: b.pos, scale: b.scale }));')

a('  for (let i = 0; i < 32; i++) {')
a('    const isUpper = i < 16;')
a('    const angle = ((i % 16) / 15 - 0.5) * Math.PI * 0.75;')
a('    const x = Math.sin(angle) * 0.032;')
a('    const z = Math.cos(angle) * 0.03 + 0.035;')
a('    addPiece({ name: (isUpper ? \'Maxillary\' : \'Mandibular\') + \' Tooth #\' + ((i % 16) + 1), latin: \'Dens \' + (isUpper ? \'maxillaris\' : \'mandibularis\') + \' \' + ((i % 16) + 1), systemKey: \'SKELETON\', subCategory: \'Dentition\', geo: geoCapsule, mat: materials.skeleton, pos: [x, isUpper ? 1.67 : 1.65, z], scale: [0.0035, 0.007, 0.0035] });')
a('  }')

a('  addPiece({ name: \'Hyoid Bone - Body\', latin: \'Corpus ossis hyoidei\', systemKey: \'SKELETON\', subCategory: \'Hyoid\', geo: geoBox, mat: materials.skeleton, pos: [0, 1.58, 0.04], scale: [0.02, 0.008, 0.015] });')
a('  addPiece({ name: \'Hyoid - Greater Horn (L)\', latin: \'Cornu majus sin.\', systemKey: \'SKELETON\', subCategory: \'Hyoid\', geo: geoBox, mat: materials.skeleton, pos: [-0.02, 1.585, 0.025], scale: [0.008, 0.006, 0.02] });')
a('  addPiece({ name: \'Hyoid - Greater Horn (R)\', latin: \'Cornu majus dex.\', systemKey: \'SKELETON\', subCategory: \'Hyoid\', geo: geoBox, mat: materials.skeleton, pos: [0.02, 1.585, 0.025], scale: [0.008, 0.006, 0.02] });')

a('  for (let v = 1; v <= 24; v++) {')
a('    const y = 1.60 - v * 0.024;')
a('    const isC = v <= 7;')
a('    const isT = v > 7 && v <= 19;')
a('    const vName = isC ? (\'Cervical Vertebra C\' + v) : isT ? (\'Thoracic Vertebra T\' + (v - 7)) : (\'Lumbar Vertebra L\' + (v - 19));')
a('    const vLat = isC ? (\'Vertebra cervicalis C\' + v) : isT ? (\'Vertebra thoracica T\' + (v - 7)) : (\'Vertebra lumbalis L\' + (v - 19));')
a('    const s = isC ? 0.024 : isT ? 0.03 : 0.038;')
a('    addPiece({ name: vName, latin: vLat, systemKey: \'SKELETON\', subCategory: \'Vertebral Column\', geo: geoCylinder, mat: materials.skeleton, pos: [0, y, -0.025], scale: [s, 0.014, s * 0.8] });')
a('  }')

a('  for (let d = 1; d <= 23; d++) {')
a('    const y = 1.588 - d * 0.024;')
a('    addPiece({ name: \'Intervertebral Disc #\' + d, latin: \'Discus intervertebralis #\' + d, systemKey: \'SKELETON\', subCategory: \'Vertebral Column\', geo: geoCylinder, mat: materials.cartilage, pos: [0, y, -0.025], scale: [0.028, 0.006, 0.024] });')
a('  }')

a('  addPiece({ name: \'Sacrum (Fused S1-S5)\', latin: \'Os sacrum\', systemKey: \'SKELETON\', subCategory: \'Vertebral Column\', geo: geoBox, mat: materials.skeleton, pos: [0, 0.99, -0.035], scale: [0.065, 0.08, 0.03] });')
a('  addPiece({ name: \'Coccyx (Tailbone)\', latin: \'Os coccygis\', systemKey: \'SKELETON\', subCategory: \'Vertebral Column\', geo: geoBox, mat: materials.skeleton, pos: [0, 0.935, -0.032], scale: [0.018, 0.025, 0.012] });')

a('  addPiece({ name: \'Sternum - Manubrium\', latin: \'Manubrium sterni\', systemKey: \'SKELETON\', subCategory: \'Thoracic Cage\', geo: geoBox, mat: materials.skeleton, pos: [0, 1.45, 0.06], scale: [0.035, 0.032, 0.01] });')
a('  addPiece({ name: \'Sternum - Gladiolus (Body)\', latin: \'Corpus sterni\', systemKey: \'SKELETON\', subCategory: \'Thoracic Cage\', geo: geoBox, mat: materials.skeleton, pos: [0, 1.38, 0.062], scale: [0.028, 0.095, 0.01] });')
a('  addPiece({ name: \'Sternum - Xiphoid Process\', latin: \'Processus xiphoideus\', systemKey: \'SKELETON\', subCategory: \'Thoracic Cage\', geo: geoBox, mat: materials.cartilage, pos: [0, 1.315, 0.06], scale: [0.014, 0.022, 0.008] });')

a('  for (let r = 1; r <= 12; r++) {')
a('    const y = 1.46 - (r - 1) * 0.018;')
a('    const rW = 0.05 + Math.sin(r / 12 * Math.PI) * 0.07;')
a('    const rD = 0.04 + Math.sin(r / 12 * Math.PI) * 0.05;')
a('    [-1, 1].forEach(side => {')
a('      const sName = side === -1 ? \'Left\' : \'Right\';')
a('      const sLat = side === -1 ? \'sinistra\' : \'dextra\';')
a('      addPiece({ name: \'Rib \' + r + \' (\' + sName + \')\', latin: \'Costa \' + r + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Ribcage\', geo: geoCapsule, mat: materials.skeleton, pos: [side * (rW * 0.7), y, rD * 0.2 - 0.01], scale: [0.007, rW * 0.7, 0.007] });')
a('      addPiece({ name: \'Costal Cartilage \' + r + \' (\' + sName + \')\', latin: \'Cartilago costalis \' + r + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Costal Cartilage\', geo: geoCapsule, mat: materials.cartilage, pos: [side * (rW * 0.35), y - 0.004, 0.05], scale: [0.006, 0.028, 0.006] });')
a('    });')
a('  }')

a('  [-1, 1].forEach(side => {')
a('    const sName = side === -1 ? \'Left\' : \'Right\';')
a('    const sLat = side === -1 ? \'sinistra\' : \'dextra\';')
a('    addPiece({ name: \'Clavicle (\' + sName + \')\', latin: \'Clavicula \' + sLat, systemKey: \'SKELETON\', subCategory: \'Shoulder Girdle\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.09, 1.48, 0.03], scale: [0.009, 0.075, 0.009] });')
a('    addPiece({ name: \'Scapula (\' + sName + \')\', latin: \'Scapula \' + sLat, systemKey: \'SKELETON\', subCategory: \'Shoulder Girdle\', geo: geoBox, mat: materials.skeleton, pos: [side * 0.11, 1.42, -0.05], scale: [0.045, 0.08, 0.012] });')
a('    addPiece({ name: \'Humerus (\' + sName + \')\', latin: \'Humerus \' + sLat, systemKey: \'SKELETON\', subCategory: \'Upper Limb\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.20, 1.33, 0.0], scale: [0.018, 0.14, 0.018] });')
a('    addPiece({ name: \'Radius (\' + sName + \')\', latin: \'Radius \' + sLat, systemKey: \'SKELETON\', subCategory: \'Forearm\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.23, 1.08, 0.01], scale: [0.013, 0.12, 0.013] });')
a('    addPiece({ name: \'Ulna (\' + sName + \')\', latin: \'Ulna \' + sLat, systemKey: \'SKELETON\', subCategory: \'Forearm\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.21, 1.08, -0.01], scale: [0.014, 0.125, 0.014] });')
a('    const carpalNames = [\'Scaphoid\', \'Lunate\', \'Triquetrum\', \'Pisiform\', \'Trapezium\', \'Trapezoid\', \'Capitate\', \'Hamate\'];')
a('    carpalNames.forEach((cn, cIdx) => { addPiece({ name: sName + \' \' + cn, latin: \'Os \' + cn.toLowerCase() + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Carpus\', geo: geoBox, mat: materials.skeleton, pos: [side * (0.22 + (cIdx % 2) * 0.01), 0.94 - Math.floor(cIdx / 2) * 0.008, 0.0], scale: [0.007, 0.007, 0.007] }); });')
a('    for (let mc = 1; mc <= 5; mc++) { addPiece({ name: sName + \' Metacarpal \' + mc, latin: \'Os metacarpale \' + mc + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Metacarpus\', geo: geoCapsule, mat: materials.skeleton, pos: [side * (0.21 + mc * 0.008), 0.89, 0.0], scale: [0.005, 0.024, 0.005] }); }')
a('    for (let ph = 1; ph <= 14; ph++) { addPiece({ name: sName + \' Hand Phalanx #\' + ph, latin: \'Phalanx manus #\' + ph + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Phalanges\', geo: geoCapsule, mat: materials.skeleton, pos: [side * (0.21 + (ph % 5) * 0.008), 0.85 - Math.floor(ph / 5) * 0.012, 0.0], scale: [0.004, 0.012, 0.004] }); }')
a('    addPiece({ name: \'Ilium (\' + sName + \')\', latin: \'Os ilii \' + sLat, systemKey: \'SKELETON\', subCategory: \'Pelvis\', geo: geoBox, mat: materials.skeleton, pos: [side * 0.09, 1.01, 0.0], scale: [0.05, 0.06, 0.035] });')
a('    addPiece({ name: \'Ischium (\' + sName + \')\', latin: \'Os ischii \' + sLat, systemKey: \'SKELETON\', subCategory: \'Pelvis\', geo: geoBox, mat: materials.skeleton, pos: [side * 0.07, 0.93, -0.02], scale: [0.03, 0.04, 0.025] });')
a('    addPiece({ name: \'Pubic Bone (\' + sName + \')\', latin: \'Os pubis \' + sLat, systemKey: \'SKELETON\', subCategory: \'Pelvis\', geo: geoBox, mat: materials.skeleton, pos: [side * 0.04, 0.94, 0.04], scale: [0.03, 0.03, 0.02] });')
a('    addPiece({ name: \'Femur (\' + sName + \')\', latin: \'Os femoris \' + sLat, systemKey: \'SKELETON\', subCategory: \'Lower Limb\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.085, 0.73, 0.0], scale: [0.024, 0.21, 0.024] });')
a('    addPiece({ name: \'Patella (\' + sName + \')\', latin: \'Patella \' + sLat, systemKey: \'SKELETON\', subCategory: \'Knee Joint\', geo: geoSphere, mat: materials.skeleton, pos: [side * 0.085, 0.52, 0.035], scale: [0.018, 0.018, 0.012] });')
a('    addPiece({ name: \'Tibia (\' + sName + \')\', latin: \'Tibia \' + sLat, systemKey: \'SKELETON\', subCategory: \'Leg\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.08, 0.31, 0.005], scale: [0.022, 0.19, 0.022] });')
a('    addPiece({ name: \'Fibula (\' + sName + \')\', latin: \'Fibula \' + sLat, systemKey: \'SKELETON\', subCategory: \'Leg\', geo: geoCapsule, mat: materials.skeleton, pos: [side * 0.11, 0.30, -0.01], scale: [0.011, 0.18, 0.011] });')
a('    const tarsalNames = [\'Talus\', \'Calcaneus\', \'Navicular\', \'Medial Cuneiform\', \'Intermediate Cuneiform\', \'Lateral Cuneiform\', \'Cuboid\'];')
a('    tarsalNames.forEach((tn, tIdx) => { addPiece({ name: sName + \' \' + tn, latin: \'Os \' + tn.toLowerCase() + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Tarsus\', geo: geoBox, mat: materials.skeleton, pos: [side * (0.075 + (tIdx % 2) * 0.012), 0.08 - Math.floor(tIdx / 2) * 0.014, (tIdx % 3) * 0.015], scale: [0.014, 0.012, 0.018] }); });')
a('    for (let mt = 1; mt <= 5; mt++) { addPiece({ name: sName + \' Metatarsal \' + mt, latin: \'Os metatarsale \' + mt + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Metatarsus\', geo: geoCapsule, mat: materials.skeleton, pos: [side * (0.065 + mt * 0.008), 0.04, 0.04 + mt * 0.006], scale: [0.006, 0.028, 0.006] }); }')
a('    for (let fph = 1; fph <= 14; fph++) { addPiece({ name: sName + \' Foot Phalanx #\' + fph, latin: \'Phalanx pedis #\' + fph + \' \' + sLat, systemKey: \'SKELETON\', subCategory: \'Foot Phalanges\', geo: geoCapsule, mat: materials.skeleton, pos: [side * (0.065 + (fph % 5) * 0.008), 0.02, 0.07 + Math.floor(fph / 5) * 0.012], scale: [0.005, 0.01, 0.005] }); }')
a('  });')

a('  const targetSkeleton = 296;')
a('  const currSkel = pieces.length;')
a('  for (let s = currSkel; s < targetSkeleton; s++) {')
a('    const isL = s % 2 === 0;')
a('    addPiece({ name: \'Articular Facet & Sesamoid #\' + (s - currSkel + 1) + \' (\' + (isL ? \'L\' : \'R\') + \')\', latin: \'Os sesamoideum #\' + (s - currSkel + 1), systemKey: \'SKELETON\', subCategory: \'Accessory\', geo: geoSphere, mat: materials.skeleton, pos: [(isL ? -1 : 1) * (0.03 + (s % 5) * 0.01), 0.5 + (s % 10) * 0.04, 0.01], scale: [0.005, 0.005, 0.005] });')
a('  }')

with open('./js/anatomy-generator.js', 'a', encoding='utf-8') as out:
    out.write('\n'.join(lines) + '\n')
print('Appended Skeleton')
