# Build anatomy generator with exact piece counts
import math

lines = []
def add(s):
    lines.append(s)

add('import * as THREE from \'three\';')
add('import { ANATOMICAL_SYSTEMS, getAnatomicalDossier } from \'./anatomy-data.js\';')
add('')
add('export function generateAnatomyModel() {')
add('  const pieces = [];')
add('  const materials = {')
add('    skeleton: new THREE.MeshStandardMaterial({ color: 0xeeece2, roughness: 0.38, metalness: 0.08, name: \'mat_skeleton\' }),')
add('    cartilage: new THREE.MeshStandardMaterial({ color: 0xd9e2ec, roughness: 0.25, metalness: 0.05, transparent: true, opacity: 0.85, name: \'mat_cartilage\' }),')
add('    muscles: new THREE.MeshStandardMaterial({ color: 0xc8423f, roughness: 0.55, metalness: 0.06, name: \'mat_muscles\' }),')
add('    tendon: new THREE.MeshStandardMaterial({ color: 0xf1efe7, roughness: 0.3, metalness: 0.04, name: \'mat_tendon\' }),')
add('    heart: new THREE.MeshStandardMaterial({ color: 0xcc2936, roughness: 0.35, metalness: 0.12, name: \'mat_heart\' }),')
add('    sensory: new THREE.MeshStandardMaterial({ color: 0x4f46e5, roughness: 0.25, metalness: 0.15, name: \'mat_sensory\' }),')
add('    arteries: new THREE.MeshStandardMaterial({ color: 0xdc2626, roughness: 0.28, metalness: 0.2, name: \'mat_arteries\' }),')
add('    veins: new THREE.MeshStandardMaterial({ color: 0x2563eb, roughness: 0.28, metalness: 0.2, name: \'mat_veins\' }),')
add('    nervous: new THREE.MeshStandardMaterial({ color: 0xf59e0b, roughness: 0.32, metalness: 0.15, name: \'mat_nervous\' }),')
add('    respiratory: new THREE.MeshStandardMaterial({ color: 0x9333ea, roughness: 0.4, metalness: 0.08, name: \'mat_respiratory\' }),')
add('    digestive: new THREE.MeshStandardMaterial({ color: 0xe07a5f, roughness: 0.38, metalness: 0.1, name: \'mat_digestive\' }),')
add('    urinary: new THREE.MeshStandardMaterial({ color: 0x0891b2, roughness: 0.35, metalness: 0.12, name: \'mat_urinary\' }),')
add('    lymphatic: new THREE.MeshStandardMaterial({ color: 0x16a34a, roughness: 0.35, metalness: 0.15, name: \'mat_lymphatic\' }),')
add('    integumentary: new THREE.MeshStandardMaterial({ color: 0xdfb08b, roughness: 0.6, metalness: 0.04, transparent: true, opacity: 0.95, name: \'mat_integumentary\' })')
add('  };')
add('  const geoBox = new THREE.BoxGeometry(1, 1, 1);')
add('  const geoCylinder = new THREE.CylinderGeometry(1, 1, 1, 16);')
add('  const geoSphere = new THREE.SphereGeometry(1, 16, 16);')
add('  const geoCapsule = new THREE.CapsuleGeometry(1, 1, 8, 16);')
add('  const COLS = 64;')
add('  const SPACING_X = 0.052;')
add('  const SPACING_Y = 0.065;')
add('  const TOP_Y = 1.95;')
add('  function addPiece({ name, latin, systemKey, subCategory, geo, mat, pos=[0,0,0], rot=[0,0,0], scale=[1,1,1] }) {')
add('    const mesh = new THREE.Mesh(geo, mat);')
add('    mesh.position.set(pos[0], pos[1], pos[2]);')
add('    mesh.rotation.set(rot[0], rot[1], rot[2]);')
add('    mesh.scale.set(scale[0], scale[1], scale[2]);')
add('    mesh.castShadow = true;')
add('    mesh.receiveShadow = true;')
add('    const idx = pieces.length;')
add('    const col = idx % COLS;')
add('    const row = Math.floor(idx / COLS);')
add('    const gridX = (col - (COLS - 1) / 2) * SPACING_X;')
add('    const gridY = TOP_Y - row * SPACING_Y;')
add('    const gridZ = 0.0;')
add('    mesh.userData = {')
add('      id: \'piece_\' + (idx + 1),')
add('      index: idx,')
add('      name: name,')
add('      latin: latin || name,')
add('      systemKey: systemKey,')
add('      systemName: ANATOMICAL_SYSTEMS[systemKey]?.name || systemKey,')
add('      subCategory: subCategory || \'\',')
add('      basePos: mesh.position.clone(),')
add('      baseRot: mesh.rotation.clone(),')
add('      explodedPos: new THREE.Vector3(gridX, gridY, gridZ),')
add('      explodedRot: new THREE.Euler(0, 0, 0),')
add('      originalMaterial: mat,')
add('      dossier: getAnatomicalDossier(name, systemKey, subCategory)')
add('    };')
add('    pieces.push(mesh);')
add('    return mesh;')
add('  }')

with open('./js/anatomy-generator.js', 'w', encoding='utf-8') as out:
    out.write('\n'.join(lines) + '\n')
print('Generator header ready')
